# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CloudAccountVsphereSpecification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host_name': 'str',
        'accept_self_signed_certificate': 'bool',
        'associated_cloud_account_ids': 'list[str]',
        'password': 'str',
        'create_default_zones': 'bool',
        'dcid': 'str',
        'name': 'str',
        'description': 'str',
        'region_ids': 'list[str]',
        'username': 'str',
        'tags': 'list[Tag]'
    }

    attribute_map = {
        'host_name': 'hostName',
        'accept_self_signed_certificate': 'acceptSelfSignedCertificate',
        'associated_cloud_account_ids': 'associatedCloudAccountIds',
        'password': 'password',
        'create_default_zones': 'createDefaultZones',
        'dcid': 'dcid',
        'name': 'name',
        'description': 'description',
        'region_ids': 'regionIds',
        'username': 'username',
        'tags': 'tags'
    }

    def __init__(self, host_name=None, accept_self_signed_certificate=None, associated_cloud_account_ids=None, password=None, create_default_zones=None, dcid=None, name=None, description=None, region_ids=None, username=None, tags=None):  # noqa: E501
        """CloudAccountVsphereSpecification - a model defined in Swagger"""  # noqa: E501

        self._host_name = None
        self._accept_self_signed_certificate = None
        self._associated_cloud_account_ids = None
        self._password = None
        self._create_default_zones = None
        self._dcid = None
        self._name = None
        self._description = None
        self._region_ids = None
        self._username = None
        self._tags = None
        self.discriminator = None

        self.host_name = host_name
        if accept_self_signed_certificate is not None:
            self.accept_self_signed_certificate = accept_self_signed_certificate
        if associated_cloud_account_ids is not None:
            self.associated_cloud_account_ids = associated_cloud_account_ids
        self.password = password
        if create_default_zones is not None:
            self.create_default_zones = create_default_zones
        if dcid is not None:
            self.dcid = dcid
        self.name = name
        if description is not None:
            self.description = description
        self.region_ids = region_ids
        self.username = username
        if tags is not None:
            self.tags = tags

    @property
    def host_name(self):
        """Gets the host_name of this CloudAccountVsphereSpecification.  # noqa: E501

        Host name for the vSphere endpoint  # noqa: E501

        :return: The host_name of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: str
        """
        return self._host_name

    @host_name.setter
    def host_name(self, host_name):
        """Sets the host_name of this CloudAccountVsphereSpecification.

        Host name for the vSphere endpoint  # noqa: E501

        :param host_name: The host_name of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: str
        """
        if host_name is None:
            raise ValueError("Invalid value for `host_name`, must not be `None`")  # noqa: E501

        self._host_name = host_name

    @property
    def accept_self_signed_certificate(self):
        """Gets the accept_self_signed_certificate of this CloudAccountVsphereSpecification.  # noqa: E501

        Accept self signed certificate when connecting to vSphere  # noqa: E501

        :return: The accept_self_signed_certificate of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: bool
        """
        return self._accept_self_signed_certificate

    @accept_self_signed_certificate.setter
    def accept_self_signed_certificate(self, accept_self_signed_certificate):
        """Sets the accept_self_signed_certificate of this CloudAccountVsphereSpecification.

        Accept self signed certificate when connecting to vSphere  # noqa: E501

        :param accept_self_signed_certificate: The accept_self_signed_certificate of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: bool
        """

        self._accept_self_signed_certificate = accept_self_signed_certificate

    @property
    def associated_cloud_account_ids(self):
        """Gets the associated_cloud_account_ids of this CloudAccountVsphereSpecification.  # noqa: E501

        Cloud accounts to associate with this cloud account  # noqa: E501

        :return: The associated_cloud_account_ids of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: list[str]
        """
        return self._associated_cloud_account_ids

    @associated_cloud_account_ids.setter
    def associated_cloud_account_ids(self, associated_cloud_account_ids):
        """Sets the associated_cloud_account_ids of this CloudAccountVsphereSpecification.

        Cloud accounts to associate with this cloud account  # noqa: E501

        :param associated_cloud_account_ids: The associated_cloud_account_ids of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: list[str]
        """

        self._associated_cloud_account_ids = associated_cloud_account_ids

    @property
    def password(self):
        """Gets the password of this CloudAccountVsphereSpecification.  # noqa: E501

        Password for the user used to authenticate with the cloud Account  # noqa: E501

        :return: The password of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this CloudAccountVsphereSpecification.

        Password for the user used to authenticate with the cloud Account  # noqa: E501

        :param password: The password of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def create_default_zones(self):
        """Gets the create_default_zones of this CloudAccountVsphereSpecification.  # noqa: E501

        Create default cloud zones for the enabled regions.  # noqa: E501

        :return: The create_default_zones of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: bool
        """
        return self._create_default_zones

    @create_default_zones.setter
    def create_default_zones(self, create_default_zones):
        """Sets the create_default_zones of this CloudAccountVsphereSpecification.

        Create default cloud zones for the enabled regions.  # noqa: E501

        :param create_default_zones: The create_default_zones of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: bool
        """

        self._create_default_zones = create_default_zones

    @property
    def dcid(self):
        """Gets the dcid of this CloudAccountVsphereSpecification.  # noqa: E501

        Identifier of a data collector vm deployed in the on premise infrastructure. Refer to the data-collector API to create or list data collectors  # noqa: E501

        :return: The dcid of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: str
        """
        return self._dcid

    @dcid.setter
    def dcid(self, dcid):
        """Sets the dcid of this CloudAccountVsphereSpecification.

        Identifier of a data collector vm deployed in the on premise infrastructure. Refer to the data-collector API to create or list data collectors  # noqa: E501

        :param dcid: The dcid of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: str
        """

        self._dcid = dcid

    @property
    def name(self):
        """Gets the name of this CloudAccountVsphereSpecification.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CloudAccountVsphereSpecification.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this CloudAccountVsphereSpecification.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CloudAccountVsphereSpecification.

        A human-friendly description.  # noqa: E501

        :param description: The description of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def region_ids(self):
        """Gets the region_ids of this CloudAccountVsphereSpecification.  # noqa: E501

        A set of datacenter managed object reference identifiers (MoRef) to enable provisioning on. Refer to /iaas/cloud-accounts-vsphere/region-enumeration.  # noqa: E501

        :return: The region_ids of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: list[str]
        """
        return self._region_ids

    @region_ids.setter
    def region_ids(self, region_ids):
        """Sets the region_ids of this CloudAccountVsphereSpecification.

        A set of datacenter managed object reference identifiers (MoRef) to enable provisioning on. Refer to /iaas/cloud-accounts-vsphere/region-enumeration.  # noqa: E501

        :param region_ids: The region_ids of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: list[str]
        """
        if region_ids is None:
            raise ValueError("Invalid value for `region_ids`, must not be `None`")  # noqa: E501

        self._region_ids = region_ids

    @property
    def username(self):
        """Gets the username of this CloudAccountVsphereSpecification.  # noqa: E501

        Username to authenticate with the cloud account  # noqa: E501

        :return: The username of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this CloudAccountVsphereSpecification.

        Username to authenticate with the cloud account  # noqa: E501

        :param username: The username of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def tags(self):
        """Gets the tags of this CloudAccountVsphereSpecification.  # noqa: E501

        A set of tag keys and optional values to set on the Cloud Account  # noqa: E501

        :return: The tags of this CloudAccountVsphereSpecification.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CloudAccountVsphereSpecification.

        A set of tag keys and optional values to set on the Cloud Account  # noqa: E501

        :param tags: The tags of this CloudAccountVsphereSpecification.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloudAccountVsphereSpecification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudAccountVsphereSpecification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
