# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CloudAccountSpecification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cloud_account_properties': 'dict(str, str)',
        'private_key': 'str',
        'associated_cloud_account_ids': 'list[str]',
        'create_default_zones': 'bool',
        'custom_properties': 'dict(str, str)',
        'cloud_account_type': 'str',
        'name': 'str',
        'description': 'str',
        'region_ids': 'list[str]',
        'private_key_id': 'str',
        'tags': 'list[Tag]'
    }

    attribute_map = {
        'cloud_account_properties': 'cloudAccountProperties',
        'private_key': 'privateKey',
        'associated_cloud_account_ids': 'associatedCloudAccountIds',
        'create_default_zones': 'createDefaultZones',
        'custom_properties': 'customProperties',
        'cloud_account_type': 'cloudAccountType',
        'name': 'name',
        'description': 'description',
        'region_ids': 'regionIds',
        'private_key_id': 'privateKeyId',
        'tags': 'tags'
    }

    def __init__(self, cloud_account_properties=None, private_key=None, associated_cloud_account_ids=None, create_default_zones=None, custom_properties=None, cloud_account_type=None, name=None, description=None, region_ids=None, private_key_id=None, tags=None):  # noqa: E501
        """CloudAccountSpecification - a model defined in Swagger"""  # noqa: E501

        self._cloud_account_properties = None
        self._private_key = None
        self._associated_cloud_account_ids = None
        self._create_default_zones = None
        self._custom_properties = None
        self._cloud_account_type = None
        self._name = None
        self._description = None
        self._region_ids = None
        self._private_key_id = None
        self._tags = None
        self.discriminator = None

        self.cloud_account_properties = cloud_account_properties
        self.private_key = private_key
        if associated_cloud_account_ids is not None:
            self.associated_cloud_account_ids = associated_cloud_account_ids
        if create_default_zones is not None:
            self.create_default_zones = create_default_zones
        if custom_properties is not None:
            self.custom_properties = custom_properties
        self.cloud_account_type = cloud_account_type
        self.name = name
        if description is not None:
            self.description = description
        self.region_ids = region_ids
        self.private_key_id = private_key_id
        if tags is not None:
            self.tags = tags

    @property
    def cloud_account_properties(self):
        """Gets the cloud_account_properties of this CloudAccountSpecification.  # noqa: E501

        Cloud Account specific properties supplied in as name value pairs  # noqa: E501

        :return: The cloud_account_properties of this CloudAccountSpecification.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._cloud_account_properties

    @cloud_account_properties.setter
    def cloud_account_properties(self, cloud_account_properties):
        """Sets the cloud_account_properties of this CloudAccountSpecification.

        Cloud Account specific properties supplied in as name value pairs  # noqa: E501

        :param cloud_account_properties: The cloud_account_properties of this CloudAccountSpecification.  # noqa: E501
        :type: dict(str, str)
        """
        if cloud_account_properties is None:
            raise ValueError("Invalid value for `cloud_account_properties`, must not be `None`")  # noqa: E501

        self._cloud_account_properties = cloud_account_properties

    @property
    def private_key(self):
        """Gets the private_key of this CloudAccountSpecification.  # noqa: E501

        Secret access key or password to be used to authenticate with the cloud account  # noqa: E501

        :return: The private_key of this CloudAccountSpecification.  # noqa: E501
        :rtype: str
        """
        return self._private_key

    @private_key.setter
    def private_key(self, private_key):
        """Sets the private_key of this CloudAccountSpecification.

        Secret access key or password to be used to authenticate with the cloud account  # noqa: E501

        :param private_key: The private_key of this CloudAccountSpecification.  # noqa: E501
        :type: str
        """
        if private_key is None:
            raise ValueError("Invalid value for `private_key`, must not be `None`")  # noqa: E501

        self._private_key = private_key

    @property
    def associated_cloud_account_ids(self):
        """Gets the associated_cloud_account_ids of this CloudAccountSpecification.  # noqa: E501

        Cloud account to link with this cloud account  # noqa: E501

        :return: The associated_cloud_account_ids of this CloudAccountSpecification.  # noqa: E501
        :rtype: list[str]
        """
        return self._associated_cloud_account_ids

    @associated_cloud_account_ids.setter
    def associated_cloud_account_ids(self, associated_cloud_account_ids):
        """Sets the associated_cloud_account_ids of this CloudAccountSpecification.

        Cloud account to link with this cloud account  # noqa: E501

        :param associated_cloud_account_ids: The associated_cloud_account_ids of this CloudAccountSpecification.  # noqa: E501
        :type: list[str]
        """

        self._associated_cloud_account_ids = associated_cloud_account_ids

    @property
    def create_default_zones(self):
        """Gets the create_default_zones of this CloudAccountSpecification.  # noqa: E501

        Create default cloud zones for the enabled regions.  # noqa: E501

        :return: The create_default_zones of this CloudAccountSpecification.  # noqa: E501
        :rtype: bool
        """
        return self._create_default_zones

    @create_default_zones.setter
    def create_default_zones(self, create_default_zones):
        """Sets the create_default_zones of this CloudAccountSpecification.

        Create default cloud zones for the enabled regions.  # noqa: E501

        :param create_default_zones: The create_default_zones of this CloudAccountSpecification.  # noqa: E501
        :type: bool
        """

        self._create_default_zones = create_default_zones

    @property
    def custom_properties(self):
        """Gets the custom_properties of this CloudAccountSpecification.  # noqa: E501

        Additional custom properties that may be used to extend the Cloud Account.  # noqa: E501

        :return: The custom_properties of this CloudAccountSpecification.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._custom_properties

    @custom_properties.setter
    def custom_properties(self, custom_properties):
        """Sets the custom_properties of this CloudAccountSpecification.

        Additional custom properties that may be used to extend the Cloud Account.  # noqa: E501

        :param custom_properties: The custom_properties of this CloudAccountSpecification.  # noqa: E501
        :type: dict(str, str)
        """

        self._custom_properties = custom_properties

    @property
    def cloud_account_type(self):
        """Gets the cloud_account_type of this CloudAccountSpecification.  # noqa: E501

        Cloud account type  # noqa: E501

        :return: The cloud_account_type of this CloudAccountSpecification.  # noqa: E501
        :rtype: str
        """
        return self._cloud_account_type

    @cloud_account_type.setter
    def cloud_account_type(self, cloud_account_type):
        """Sets the cloud_account_type of this CloudAccountSpecification.

        Cloud account type  # noqa: E501

        :param cloud_account_type: The cloud_account_type of this CloudAccountSpecification.  # noqa: E501
        :type: str
        """
        if cloud_account_type is None:
            raise ValueError("Invalid value for `cloud_account_type`, must not be `None`")  # noqa: E501

        self._cloud_account_type = cloud_account_type

    @property
    def name(self):
        """Gets the name of this CloudAccountSpecification.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this CloudAccountSpecification.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CloudAccountSpecification.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this CloudAccountSpecification.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this CloudAccountSpecification.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this CloudAccountSpecification.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CloudAccountSpecification.

        A human-friendly description.  # noqa: E501

        :param description: The description of this CloudAccountSpecification.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def region_ids(self):
        """Gets the region_ids of this CloudAccountSpecification.  # noqa: E501

        A set of Region names to enable provisioning on.Refer to /iaas/cloud-accounts/region-enumeration.  # noqa: E501

        :return: The region_ids of this CloudAccountSpecification.  # noqa: E501
        :rtype: list[str]
        """
        return self._region_ids

    @region_ids.setter
    def region_ids(self, region_ids):
        """Sets the region_ids of this CloudAccountSpecification.

        A set of Region names to enable provisioning on.Refer to /iaas/cloud-accounts/region-enumeration.  # noqa: E501

        :param region_ids: The region_ids of this CloudAccountSpecification.  # noqa: E501
        :type: list[str]
        """
        if region_ids is None:
            raise ValueError("Invalid value for `region_ids`, must not be `None`")  # noqa: E501

        self._region_ids = region_ids

    @property
    def private_key_id(self):
        """Gets the private_key_id of this CloudAccountSpecification.  # noqa: E501

        Access key id or username to be used to authenticate with the cloud account  # noqa: E501

        :return: The private_key_id of this CloudAccountSpecification.  # noqa: E501
        :rtype: str
        """
        return self._private_key_id

    @private_key_id.setter
    def private_key_id(self, private_key_id):
        """Sets the private_key_id of this CloudAccountSpecification.

        Access key id or username to be used to authenticate with the cloud account  # noqa: E501

        :param private_key_id: The private_key_id of this CloudAccountSpecification.  # noqa: E501
        :type: str
        """
        if private_key_id is None:
            raise ValueError("Invalid value for `private_key_id`, must not be `None`")  # noqa: E501

        self._private_key_id = private_key_id

    @property
    def tags(self):
        """Gets the tags of this CloudAccountSpecification.  # noqa: E501

        A set of tag keys and optional values to set on the Cloud Account  # noqa: E501

        :return: The tags of this CloudAccountSpecification.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CloudAccountSpecification.

        A set of tag keys and optional values to set on the Cloud Account  # noqa: E501

        :param tags: The tags of this CloudAccountSpecification.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloudAccountSpecification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudAccountSpecification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
