# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ImageMappingDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'cloud_config': 'str',
        'os_family': 'str',
        'links': 'dict(str, Href)',
        'external_region_id': 'str',
        'description': 'str',
        'external_id': 'str',
        'is_private': 'bool',
        'constraints': 'list[Constraint]',
        'org_id': 'str',
        'organization_id': 'str',
        'created_at': 'str',
        'cloud_account_ids': 'list[str]',
        'custom_properties': 'dict(str, str)',
        'name': 'str',
        'id': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'owner': 'owner',
        'cloud_config': 'cloudConfig',
        'os_family': 'osFamily',
        'links': '_links',
        'external_region_id': 'externalRegionId',
        'description': 'description',
        'external_id': 'externalId',
        'is_private': 'isPrivate',
        'constraints': 'constraints',
        'org_id': 'orgId',
        'organization_id': 'organizationId',
        'created_at': 'createdAt',
        'cloud_account_ids': 'cloudAccountIds',
        'custom_properties': 'customProperties',
        'name': 'name',
        'id': 'id',
        'updated_at': 'updatedAt'
    }

    def __init__(self, owner=None, cloud_config=None, os_family=None, links=None, external_region_id=None, description=None, external_id=None, is_private=None, constraints=None, org_id=None, organization_id=None, created_at=None, cloud_account_ids=None, custom_properties=None, name=None, id=None, updated_at=None):  # noqa: E501
        """ImageMappingDescription - a model defined in Swagger"""  # noqa: E501

        self._owner = None
        self._cloud_config = None
        self._os_family = None
        self._links = None
        self._external_region_id = None
        self._description = None
        self._external_id = None
        self._is_private = None
        self._constraints = None
        self._org_id = None
        self._organization_id = None
        self._created_at = None
        self._cloud_account_ids = None
        self._custom_properties = None
        self._name = None
        self._id = None
        self._updated_at = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if cloud_config is not None:
            self.cloud_config = cloud_config
        if os_family is not None:
            self.os_family = os_family
        self.links = links
        if external_region_id is not None:
            self.external_region_id = external_region_id
        if description is not None:
            self.description = description
        if external_id is not None:
            self.external_id = external_id
        if is_private is not None:
            self.is_private = is_private
        if constraints is not None:
            self.constraints = constraints
        if org_id is not None:
            self.org_id = org_id
        if organization_id is not None:
            self.organization_id = organization_id
        if created_at is not None:
            self.created_at = created_at
        if cloud_account_ids is not None:
            self.cloud_account_ids = cloud_account_ids
        if custom_properties is not None:
            self.custom_properties = custom_properties
        if name is not None:
            self.name = name
        self.id = id
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this ImageMappingDescription.  # noqa: E501

        Email of the user that owns the entity.  # noqa: E501

        :return: The owner of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this ImageMappingDescription.

        Email of the user that owns the entity.  # noqa: E501

        :param owner: The owner of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def cloud_config(self):
        """Gets the cloud_config of this ImageMappingDescription.  # noqa: E501

        Cloud config for this image. This cloud config will be merged during provisioning with other cloud configurations such as the bootConfig provided in MachineSpecification.  # noqa: E501

        :return: The cloud_config of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._cloud_config

    @cloud_config.setter
    def cloud_config(self, cloud_config):
        """Sets the cloud_config of this ImageMappingDescription.

        Cloud config for this image. This cloud config will be merged during provisioning with other cloud configurations such as the bootConfig provided in MachineSpecification.  # noqa: E501

        :param cloud_config: The cloud_config of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._cloud_config = cloud_config

    @property
    def os_family(self):
        """Gets the os_family of this ImageMappingDescription.  # noqa: E501

        Operating System family of the image.  # noqa: E501

        :return: The os_family of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._os_family

    @os_family.setter
    def os_family(self, os_family):
        """Sets the os_family of this ImageMappingDescription.

        Operating System family of the image.  # noqa: E501

        :param os_family: The os_family of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._os_family = os_family

    @property
    def links(self):
        """Gets the links of this ImageMappingDescription.  # noqa: E501

        HATEOAS of the entity  # noqa: E501

        :return: The links of this ImageMappingDescription.  # noqa: E501
        :rtype: dict(str, Href)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ImageMappingDescription.

        HATEOAS of the entity  # noqa: E501

        :param links: The links of this ImageMappingDescription.  # noqa: E501
        :type: dict(str, Href)
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def external_region_id(self):
        """Gets the external_region_id of this ImageMappingDescription.  # noqa: E501

        The regionId of the image  # noqa: E501

        :return: The external_region_id of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._external_region_id

    @external_region_id.setter
    def external_region_id(self, external_region_id):
        """Sets the external_region_id of this ImageMappingDescription.

        The regionId of the image  # noqa: E501

        :param external_region_id: The external_region_id of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._external_region_id = external_region_id

    @property
    def description(self):
        """Gets the description of this ImageMappingDescription.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ImageMappingDescription.

        A human-friendly description.  # noqa: E501

        :param description: The description of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def external_id(self):
        """Gets the external_id of this ImageMappingDescription.  # noqa: E501

        External entity Id on the provider side.  # noqa: E501

        :return: The external_id of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this ImageMappingDescription.

        External entity Id on the provider side.  # noqa: E501

        :param external_id: The external_id of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def is_private(self):
        """Gets the is_private of this ImageMappingDescription.  # noqa: E501

        Indicates whether this fabric image is private. For vSphere, private images are considered to be templates and snapshots and public are Content Library Items  # noqa: E501

        :return: The is_private of this ImageMappingDescription.  # noqa: E501
        :rtype: bool
        """
        return self._is_private

    @is_private.setter
    def is_private(self, is_private):
        """Sets the is_private of this ImageMappingDescription.

        Indicates whether this fabric image is private. For vSphere, private images are considered to be templates and snapshots and public are Content Library Items  # noqa: E501

        :param is_private: The is_private of this ImageMappingDescription.  # noqa: E501
        :type: bool
        """

        self._is_private = is_private

    @property
    def constraints(self):
        """Gets the constraints of this ImageMappingDescription.  # noqa: E501

        Constraints that are used to drive placement policies for the image that is produced from this mapping.Constraint expressions are matched against tags on existing placement targets.  # noqa: E501

        :return: The constraints of this ImageMappingDescription.  # noqa: E501
        :rtype: list[Constraint]
        """
        return self._constraints

    @constraints.setter
    def constraints(self, constraints):
        """Sets the constraints of this ImageMappingDescription.

        Constraints that are used to drive placement policies for the image that is produced from this mapping.Constraint expressions are matched against tags on existing placement targets.  # noqa: E501

        :param constraints: The constraints of this ImageMappingDescription.  # noqa: E501
        :type: list[Constraint]
        """

        self._constraints = constraints

    @property
    def org_id(self):
        """Gets the org_id of this ImageMappingDescription.  # noqa: E501

        The id of the organization this entity belongs to.  # noqa: E501

        :return: The org_id of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this ImageMappingDescription.

        The id of the organization this entity belongs to.  # noqa: E501

        :param org_id: The org_id of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def organization_id(self):
        """Gets the organization_id of this ImageMappingDescription.  # noqa: E501

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :return: The organization_id of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this ImageMappingDescription.

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :param organization_id: The organization_id of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def created_at(self):
        """Gets the created_at of this ImageMappingDescription.  # noqa: E501

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :return: The created_at of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ImageMappingDescription.

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :param created_at: The created_at of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def cloud_account_ids(self):
        """Gets the cloud_account_ids of this ImageMappingDescription.  # noqa: E501

        Set of ids of the cloud accounts this entity belongs to.  # noqa: E501

        :return: The cloud_account_ids of this ImageMappingDescription.  # noqa: E501
        :rtype: list[str]
        """
        return self._cloud_account_ids

    @cloud_account_ids.setter
    def cloud_account_ids(self, cloud_account_ids):
        """Sets the cloud_account_ids of this ImageMappingDescription.

        Set of ids of the cloud accounts this entity belongs to.  # noqa: E501

        :param cloud_account_ids: The cloud_account_ids of this ImageMappingDescription.  # noqa: E501
        :type: list[str]
        """

        self._cloud_account_ids = cloud_account_ids

    @property
    def custom_properties(self):
        """Gets the custom_properties of this ImageMappingDescription.  # noqa: E501

        Additional properties that may be used to extend the base type.  # noqa: E501

        :return: The custom_properties of this ImageMappingDescription.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._custom_properties

    @custom_properties.setter
    def custom_properties(self, custom_properties):
        """Sets the custom_properties of this ImageMappingDescription.

        Additional properties that may be used to extend the base type.  # noqa: E501

        :param custom_properties: The custom_properties of this ImageMappingDescription.  # noqa: E501
        :type: dict(str, str)
        """

        self._custom_properties = custom_properties

    @property
    def name(self):
        """Gets the name of this ImageMappingDescription.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ImageMappingDescription.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this ImageMappingDescription.  # noqa: E501

        The id of this resource instance  # noqa: E501

        :return: The id of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImageMappingDescription.

        The id of this resource instance  # noqa: E501

        :param id: The id of this ImageMappingDescription.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def updated_at(self):
        """Gets the updated_at of this ImageMappingDescription.  # noqa: E501

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :return: The updated_at of this ImageMappingDescription.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ImageMappingDescription.

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :param updated_at: The updated_at of this ImageMappingDescription.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageMappingDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageMappingDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
