# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NetworkInterface(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'addresses': 'list[str]',
        'links': 'dict(str, Href)',
        'external_region_id': 'str',
        'description': 'str',
        'external_id': 'str',
        'device_index': 'int',
        'org_id': 'str',
        'tags': 'list[Tag]',
        'organization_id': 'str',
        'created_at': 'str',
        'cloud_account_ids': 'list[str]',
        'custom_properties': 'dict(str, str)',
        'security_group_ids': 'list[str]',
        'name': 'str',
        'id': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'owner': 'owner',
        'addresses': 'addresses',
        'links': '_links',
        'external_region_id': 'externalRegionId',
        'description': 'description',
        'external_id': 'externalId',
        'device_index': 'deviceIndex',
        'org_id': 'orgId',
        'tags': 'tags',
        'organization_id': 'organizationId',
        'created_at': 'createdAt',
        'cloud_account_ids': 'cloudAccountIds',
        'custom_properties': 'customProperties',
        'security_group_ids': 'securityGroupIds',
        'name': 'name',
        'id': 'id',
        'updated_at': 'updatedAt'
    }

    def __init__(self, owner=None, addresses=None, links=None, external_region_id=None, description=None, external_id=None, device_index=None, org_id=None, tags=None, organization_id=None, created_at=None, cloud_account_ids=None, custom_properties=None, security_group_ids=None, name=None, id=None, updated_at=None):  # noqa: E501
        """NetworkInterface - a model defined in Swagger"""  # noqa: E501

        self._owner = None
        self._addresses = None
        self._links = None
        self._external_region_id = None
        self._description = None
        self._external_id = None
        self._device_index = None
        self._org_id = None
        self._tags = None
        self._organization_id = None
        self._created_at = None
        self._cloud_account_ids = None
        self._custom_properties = None
        self._security_group_ids = None
        self._name = None
        self._id = None
        self._updated_at = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if addresses is not None:
            self.addresses = addresses
        self.links = links
        self.external_region_id = external_region_id
        if description is not None:
            self.description = description
        if external_id is not None:
            self.external_id = external_id
        if device_index is not None:
            self.device_index = device_index
        if org_id is not None:
            self.org_id = org_id
        if tags is not None:
            self.tags = tags
        if organization_id is not None:
            self.organization_id = organization_id
        if created_at is not None:
            self.created_at = created_at
        if cloud_account_ids is not None:
            self.cloud_account_ids = cloud_account_ids
        if custom_properties is not None:
            self.custom_properties = custom_properties
        if security_group_ids is not None:
            self.security_group_ids = security_group_ids
        if name is not None:
            self.name = name
        self.id = id
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this NetworkInterface.  # noqa: E501

        Email of the user that owns the entity.  # noqa: E501

        :return: The owner of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this NetworkInterface.

        Email of the user that owns the entity.  # noqa: E501

        :param owner: The owner of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def addresses(self):
        """Gets the addresses of this NetworkInterface.  # noqa: E501

        A list of IP addresses allocated or in use by this network interface.  # noqa: E501

        :return: The addresses of this NetworkInterface.  # noqa: E501
        :rtype: list[str]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses):
        """Sets the addresses of this NetworkInterface.

        A list of IP addresses allocated or in use by this network interface.  # noqa: E501

        :param addresses: The addresses of this NetworkInterface.  # noqa: E501
        :type: list[str]
        """

        self._addresses = addresses

    @property
    def links(self):
        """Gets the links of this NetworkInterface.  # noqa: E501

        HATEOAS of the entity  # noqa: E501

        :return: The links of this NetworkInterface.  # noqa: E501
        :rtype: dict(str, Href)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this NetworkInterface.

        HATEOAS of the entity  # noqa: E501

        :param links: The links of this NetworkInterface.  # noqa: E501
        :type: dict(str, Href)
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def external_region_id(self):
        """Gets the external_region_id of this NetworkInterface.  # noqa: E501

        The external regionId of the network interface.  # noqa: E501

        :return: The external_region_id of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._external_region_id

    @external_region_id.setter
    def external_region_id(self, external_region_id):
        """Sets the external_region_id of this NetworkInterface.

        The external regionId of the network interface.  # noqa: E501

        :param external_region_id: The external_region_id of this NetworkInterface.  # noqa: E501
        :type: str
        """
        if external_region_id is None:
            raise ValueError("Invalid value for `external_region_id`, must not be `None`")  # noqa: E501

        self._external_region_id = external_region_id

    @property
    def description(self):
        """Gets the description of this NetworkInterface.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NetworkInterface.

        A human-friendly description.  # noqa: E501

        :param description: The description of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def external_id(self):
        """Gets the external_id of this NetworkInterface.  # noqa: E501

        External entity Id on the provider side.  # noqa: E501

        :return: The external_id of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this NetworkInterface.

        External entity Id on the provider side.  # noqa: E501

        :param external_id: The external_id of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def device_index(self):
        """Gets the device_index of this NetworkInterface.  # noqa: E501

        The device index of this network interface.  # noqa: E501

        :return: The device_index of this NetworkInterface.  # noqa: E501
        :rtype: int
        """
        return self._device_index

    @device_index.setter
    def device_index(self, device_index):
        """Sets the device_index of this NetworkInterface.

        The device index of this network interface.  # noqa: E501

        :param device_index: The device_index of this NetworkInterface.  # noqa: E501
        :type: int
        """

        self._device_index = device_index

    @property
    def org_id(self):
        """Gets the org_id of this NetworkInterface.  # noqa: E501

        The id of the organization this entity belongs to.  # noqa: E501

        :return: The org_id of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this NetworkInterface.

        The id of the organization this entity belongs to.  # noqa: E501

        :param org_id: The org_id of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def tags(self):
        """Gets the tags of this NetworkInterface.  # noqa: E501

        A set of tag keys and optional values that were set on this network interface.  # noqa: E501

        :return: The tags of this NetworkInterface.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this NetworkInterface.

        A set of tag keys and optional values that were set on this network interface.  # noqa: E501

        :param tags: The tags of this NetworkInterface.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def organization_id(self):
        """Gets the organization_id of this NetworkInterface.  # noqa: E501

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :return: The organization_id of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this NetworkInterface.

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :param organization_id: The organization_id of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def created_at(self):
        """Gets the created_at of this NetworkInterface.  # noqa: E501

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :return: The created_at of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this NetworkInterface.

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :param created_at: The created_at of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def cloud_account_ids(self):
        """Gets the cloud_account_ids of this NetworkInterface.  # noqa: E501

        Set of ids of the cloud accounts this entity belongs to.  # noqa: E501

        :return: The cloud_account_ids of this NetworkInterface.  # noqa: E501
        :rtype: list[str]
        """
        return self._cloud_account_ids

    @cloud_account_ids.setter
    def cloud_account_ids(self, cloud_account_ids):
        """Sets the cloud_account_ids of this NetworkInterface.

        Set of ids of the cloud accounts this entity belongs to.  # noqa: E501

        :param cloud_account_ids: The cloud_account_ids of this NetworkInterface.  # noqa: E501
        :type: list[str]
        """

        self._cloud_account_ids = cloud_account_ids

    @property
    def custom_properties(self):
        """Gets the custom_properties of this NetworkInterface.  # noqa: E501

        Additional properties that may be used to extend the base type.  # noqa: E501

        :return: The custom_properties of this NetworkInterface.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._custom_properties

    @custom_properties.setter
    def custom_properties(self, custom_properties):
        """Sets the custom_properties of this NetworkInterface.

        Additional properties that may be used to extend the base type.  # noqa: E501

        :param custom_properties: The custom_properties of this NetworkInterface.  # noqa: E501
        :type: dict(str, str)
        """

        self._custom_properties = custom_properties

    @property
    def security_group_ids(self):
        """Gets the security_group_ids of this NetworkInterface.  # noqa: E501

        A list of security group ids this network interface is associated with  # noqa: E501

        :return: The security_group_ids of this NetworkInterface.  # noqa: E501
        :rtype: list[str]
        """
        return self._security_group_ids

    @security_group_ids.setter
    def security_group_ids(self, security_group_ids):
        """Sets the security_group_ids of this NetworkInterface.

        A list of security group ids this network interface is associated with  # noqa: E501

        :param security_group_ids: The security_group_ids of this NetworkInterface.  # noqa: E501
        :type: list[str]
        """

        self._security_group_ids = security_group_ids

    @property
    def name(self):
        """Gets the name of this NetworkInterface.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NetworkInterface.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this NetworkInterface.  # noqa: E501

        The id of this resource instance  # noqa: E501

        :return: The id of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NetworkInterface.

        The id of this resource instance  # noqa: E501

        :param id: The id of this NetworkInterface.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def updated_at(self):
        """Gets the updated_at of this NetworkInterface.  # noqa: E501

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :return: The updated_at of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this NetworkInterface.

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :param updated_at: The updated_at of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkInterface, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkInterface):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
