# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Project(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'links': 'dict(str, Href)',
        'operation_timeout': 'int',
        'description': 'str',
        'zones': 'list[ZoneAssignmentConfig]',
        'constraints': 'dict(str, list[Constraint])',
        'org_id': 'str',
        'organization_id': 'str',
        'created_at': 'str',
        'viewers': 'list[User]',
        'machine_naming_template': 'str',
        'shared_resources': 'bool',
        'members': 'list[User]',
        'name': 'str',
        'id': 'str',
        'administrators': 'list[User]',
        'updated_at': 'str'
    }

    attribute_map = {
        'owner': 'owner',
        'links': '_links',
        'operation_timeout': 'operationTimeout',
        'description': 'description',
        'zones': 'zones',
        'constraints': 'constraints',
        'org_id': 'orgId',
        'organization_id': 'organizationId',
        'created_at': 'createdAt',
        'viewers': 'viewers',
        'machine_naming_template': 'machineNamingTemplate',
        'shared_resources': 'sharedResources',
        'members': 'members',
        'name': 'name',
        'id': 'id',
        'administrators': 'administrators',
        'updated_at': 'updatedAt'
    }

    def __init__(self, owner=None, links=None, operation_timeout=None, description=None, zones=None, constraints=None, org_id=None, organization_id=None, created_at=None, viewers=None, machine_naming_template=None, shared_resources=None, members=None, name=None, id=None, administrators=None, updated_at=None):  # noqa: E501
        """Project - a model defined in Swagger"""  # noqa: E501

        self._owner = None
        self._links = None
        self._operation_timeout = None
        self._description = None
        self._zones = None
        self._constraints = None
        self._org_id = None
        self._organization_id = None
        self._created_at = None
        self._viewers = None
        self._machine_naming_template = None
        self._shared_resources = None
        self._members = None
        self._name = None
        self._id = None
        self._administrators = None
        self._updated_at = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        self.links = links
        if operation_timeout is not None:
            self.operation_timeout = operation_timeout
        if description is not None:
            self.description = description
        if zones is not None:
            self.zones = zones
        if constraints is not None:
            self.constraints = constraints
        if org_id is not None:
            self.org_id = org_id
        if organization_id is not None:
            self.organization_id = organization_id
        if created_at is not None:
            self.created_at = created_at
        if viewers is not None:
            self.viewers = viewers
        if machine_naming_template is not None:
            self.machine_naming_template = machine_naming_template
        if shared_resources is not None:
            self.shared_resources = shared_resources
        if members is not None:
            self.members = members
        if name is not None:
            self.name = name
        self.id = id
        if administrators is not None:
            self.administrators = administrators
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this Project.  # noqa: E501

        Email of the user that owns the entity.  # noqa: E501

        :return: The owner of this Project.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Project.

        Email of the user that owns the entity.  # noqa: E501

        :param owner: The owner of this Project.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def links(self):
        """Gets the links of this Project.  # noqa: E501

        HATEOAS of the entity  # noqa: E501

        :return: The links of this Project.  # noqa: E501
        :rtype: dict(str, Href)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Project.

        HATEOAS of the entity  # noqa: E501

        :param links: The links of this Project.  # noqa: E501
        :type: dict(str, Href)
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def operation_timeout(self):
        """Gets the operation_timeout of this Project.  # noqa: E501

        The timeout that should be used for Blueprint operations and Provisioning tasks. The timeout is in seconds  # noqa: E501

        :return: The operation_timeout of this Project.  # noqa: E501
        :rtype: int
        """
        return self._operation_timeout

    @operation_timeout.setter
    def operation_timeout(self, operation_timeout):
        """Sets the operation_timeout of this Project.

        The timeout that should be used for Blueprint operations and Provisioning tasks. The timeout is in seconds  # noqa: E501

        :param operation_timeout: The operation_timeout of this Project.  # noqa: E501
        :type: int
        """

        self._operation_timeout = operation_timeout

    @property
    def description(self):
        """Gets the description of this Project.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this Project.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Project.

        A human-friendly description.  # noqa: E501

        :param description: The description of this Project.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def zones(self):
        """Gets the zones of this Project.  # noqa: E501

        List of Cloud Zones assigned to this project. You can limit deployment to a single region or allow multi-region placement by adding more than one cloud zone to a project. A cloud zone lists available resources. Use tags on resources to control workload placement.  # noqa: E501

        :return: The zones of this Project.  # noqa: E501
        :rtype: list[ZoneAssignmentConfig]
        """
        return self._zones

    @zones.setter
    def zones(self, zones):
        """Sets the zones of this Project.

        List of Cloud Zones assigned to this project. You can limit deployment to a single region or allow multi-region placement by adding more than one cloud zone to a project. A cloud zone lists available resources. Use tags on resources to control workload placement.  # noqa: E501

        :param zones: The zones of this Project.  # noqa: E501
        :type: list[ZoneAssignmentConfig]
        """

        self._zones = zones

    @property
    def constraints(self):
        """Gets the constraints of this Project.  # noqa: E501

        List of storage, network and extensibility constraints to be applied when provisioning through this project.  # noqa: E501

        :return: The constraints of this Project.  # noqa: E501
        :rtype: dict(str, list[Constraint])
        """
        return self._constraints

    @constraints.setter
    def constraints(self, constraints):
        """Sets the constraints of this Project.

        List of storage, network and extensibility constraints to be applied when provisioning through this project.  # noqa: E501

        :param constraints: The constraints of this Project.  # noqa: E501
        :type: dict(str, list[Constraint])
        """

        self._constraints = constraints

    @property
    def org_id(self):
        """Gets the org_id of this Project.  # noqa: E501

        The id of the organization this entity belongs to.  # noqa: E501

        :return: The org_id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this Project.

        The id of the organization this entity belongs to.  # noqa: E501

        :param org_id: The org_id of this Project.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def organization_id(self):
        """Gets the organization_id of this Project.  # noqa: E501

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :return: The organization_id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this Project.

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :param organization_id: The organization_id of this Project.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def created_at(self):
        """Gets the created_at of this Project.  # noqa: E501

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :return: The created_at of this Project.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Project.

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :param created_at: The created_at of this Project.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def viewers(self):
        """Gets the viewers of this Project.  # noqa: E501

        List of viewer users associated with the project.   # noqa: E501

        :return: The viewers of this Project.  # noqa: E501
        :rtype: list[User]
        """
        return self._viewers

    @viewers.setter
    def viewers(self, viewers):
        """Sets the viewers of this Project.

        List of viewer users associated with the project.   # noqa: E501

        :param viewers: The viewers of this Project.  # noqa: E501
        :type: list[User]
        """

        self._viewers = viewers

    @property
    def machine_naming_template(self):
        """Gets the machine_naming_template of this Project.  # noqa: E501

        The naming template to be used for machines provisioned in this project  # noqa: E501

        :return: The machine_naming_template of this Project.  # noqa: E501
        :rtype: str
        """
        return self._machine_naming_template

    @machine_naming_template.setter
    def machine_naming_template(self, machine_naming_template):
        """Sets the machine_naming_template of this Project.

        The naming template to be used for machines provisioned in this project  # noqa: E501

        :param machine_naming_template: The machine_naming_template of this Project.  # noqa: E501
        :type: str
        """

        self._machine_naming_template = machine_naming_template

    @property
    def shared_resources(self):
        """Gets the shared_resources of this Project.  # noqa: E501

        Specifies whether the resources in this projects are shared or not.  # noqa: E501

        :return: The shared_resources of this Project.  # noqa: E501
        :rtype: bool
        """
        return self._shared_resources

    @shared_resources.setter
    def shared_resources(self, shared_resources):
        """Sets the shared_resources of this Project.

        Specifies whether the resources in this projects are shared or not.  # noqa: E501

        :param shared_resources: The shared_resources of this Project.  # noqa: E501
        :type: bool
        """

        self._shared_resources = shared_resources

    @property
    def members(self):
        """Gets the members of this Project.  # noqa: E501

        List of member users associated with the project.   # noqa: E501

        :return: The members of this Project.  # noqa: E501
        :rtype: list[User]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this Project.

        List of member users associated with the project.   # noqa: E501

        :param members: The members of this Project.  # noqa: E501
        :type: list[User]
        """

        self._members = members

    @property
    def name(self):
        """Gets the name of this Project.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Project.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this Project.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this Project.  # noqa: E501

        The id of this resource instance  # noqa: E501

        :return: The id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Project.

        The id of this resource instance  # noqa: E501

        :param id: The id of this Project.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def administrators(self):
        """Gets the administrators of this Project.  # noqa: E501

        List of administrator users associated with the project. Only administrators can manage project's configuration.  # noqa: E501

        :return: The administrators of this Project.  # noqa: E501
        :rtype: list[User]
        """
        return self._administrators

    @administrators.setter
    def administrators(self, administrators):
        """Sets the administrators of this Project.

        List of administrator users associated with the project. Only administrators can manage project's configuration.  # noqa: E501

        :param administrators: The administrators of this Project.  # noqa: E501
        :type: list[User]
        """

        self._administrators = administrators

    @property
    def updated_at(self):
        """Gets the updated_at of this Project.  # noqa: E501

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :return: The updated_at of this Project.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Project.

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :param updated_at: The updated_at of this Project.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Project, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Project):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
