# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RequestTracker(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'progress': 'int',
        'resources': 'list[str]',
        'id': 'str',
        'message': 'str',
        'status': 'str',
        'self_link': 'str'
    }

    attribute_map = {
        'name': 'name',
        'progress': 'progress',
        'resources': 'resources',
        'id': 'id',
        'message': 'message',
        'status': 'status',
        'self_link': 'selfLink'
    }

    def __init__(self, name=None, progress=None, resources=None, id=None, message=None, status=None, self_link=None):  # noqa: E501
        """RequestTracker - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._progress = None
        self._resources = None
        self._id = None
        self._message = None
        self._status = None
        self._self_link = None
        self.discriminator = None

        if name is not None:
            self.name = name
        self.progress = progress
        if resources is not None:
            self.resources = resources
        self.id = id
        if message is not None:
            self.message = message
        self.status = status
        self.self_link = self_link

    @property
    def name(self):
        """Gets the name of this RequestTracker.  # noqa: E501

        Name of the operation.  # noqa: E501

        :return: The name of this RequestTracker.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RequestTracker.

        Name of the operation.  # noqa: E501

        :param name: The name of this RequestTracker.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def progress(self):
        """Gets the progress of this RequestTracker.  # noqa: E501

        Progress of the request as percentage.  # noqa: E501

        :return: The progress of this RequestTracker.  # noqa: E501
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this RequestTracker.

        Progress of the request as percentage.  # noqa: E501

        :param progress: The progress of this RequestTracker.  # noqa: E501
        :type: int
        """
        if progress is None:
            raise ValueError("Invalid value for `progress`, must not be `None`")  # noqa: E501

        self._progress = progress

    @property
    def resources(self):
        """Gets the resources of this RequestTracker.  # noqa: E501

        Collection of resources.  # noqa: E501

        :return: The resources of this RequestTracker.  # noqa: E501
        :rtype: list[str]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this RequestTracker.

        Collection of resources.  # noqa: E501

        :param resources: The resources of this RequestTracker.  # noqa: E501
        :type: list[str]
        """

        self._resources = resources

    @property
    def id(self):
        """Gets the id of this RequestTracker.  # noqa: E501

        ID of this request.  # noqa: E501

        :return: The id of this RequestTracker.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RequestTracker.

        ID of this request.  # noqa: E501

        :param id: The id of this RequestTracker.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def message(self):
        """Gets the message of this RequestTracker.  # noqa: E501

        Status message of the request.  # noqa: E501

        :return: The message of this RequestTracker.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this RequestTracker.

        Status message of the request.  # noqa: E501

        :param message: The message of this RequestTracker.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def status(self):
        """Gets the status of this RequestTracker.  # noqa: E501

        Status of the request.  # noqa: E501

        :return: The status of this RequestTracker.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this RequestTracker.

        Status of the request.  # noqa: E501

        :param status: The status of this RequestTracker.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["FINISHED", "INPROGRESS", "FAILED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def self_link(self):
        """Gets the self_link of this RequestTracker.  # noqa: E501

        Self link of this request.  # noqa: E501

        :return: The self_link of this RequestTracker.  # noqa: E501
        :rtype: str
        """
        return self._self_link

    @self_link.setter
    def self_link(self, self_link):
        """Sets the self_link of this RequestTracker.

        Self link of this request.  # noqa: E501

        :param self_link: The self_link of this RequestTracker.  # noqa: E501
        :type: str
        """
        if self_link is None:
            raise ValueError("Invalid value for `self_link`, must not be `None`")  # noqa: E501

        self._self_link = self_link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestTracker, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestTracker):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
