# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StorageProfileSpecification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disk_properties': 'dict(str, str)',
        'supports_encryption': 'bool',
        'disk_target_properties': 'dict(str, str)',
        'region_id': 'str',
        'name': 'str',
        'description': 'str',
        'default_item': 'bool',
        'tags': 'list[Tag]'
    }

    attribute_map = {
        'disk_properties': 'diskProperties',
        'supports_encryption': 'supportsEncryption',
        'disk_target_properties': 'diskTargetProperties',
        'region_id': 'regionId',
        'name': 'name',
        'description': 'description',
        'default_item': 'defaultItem',
        'tags': 'tags'
    }

    def __init__(self, disk_properties=None, supports_encryption=None, disk_target_properties=None, region_id=None, name=None, description=None, default_item=None, tags=None):  # noqa: E501
        """StorageProfileSpecification - a model defined in Swagger"""  # noqa: E501

        self._disk_properties = None
        self._supports_encryption = None
        self._disk_target_properties = None
        self._region_id = None
        self._name = None
        self._description = None
        self._default_item = None
        self._tags = None
        self.discriminator = None

        if disk_properties is not None:
            self.disk_properties = disk_properties
        if supports_encryption is not None:
            self.supports_encryption = supports_encryption
        if disk_target_properties is not None:
            self.disk_target_properties = disk_target_properties
        self.region_id = region_id
        self.name = name
        if description is not None:
            self.description = description
        self.default_item = default_item
        if tags is not None:
            self.tags = tags

    @property
    def disk_properties(self):
        """Gets the disk_properties of this StorageProfileSpecification.  # noqa: E501

        Map of storage properties that are to be applied on disk while provisioning.  # noqa: E501

        :return: The disk_properties of this StorageProfileSpecification.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._disk_properties

    @disk_properties.setter
    def disk_properties(self, disk_properties):
        """Sets the disk_properties of this StorageProfileSpecification.

        Map of storage properties that are to be applied on disk while provisioning.  # noqa: E501

        :param disk_properties: The disk_properties of this StorageProfileSpecification.  # noqa: E501
        :type: dict(str, str)
        """

        self._disk_properties = disk_properties

    @property
    def supports_encryption(self):
        """Gets the supports_encryption of this StorageProfileSpecification.  # noqa: E501

        Indicates whether this storage profile supports encryption or not.  # noqa: E501

        :return: The supports_encryption of this StorageProfileSpecification.  # noqa: E501
        :rtype: bool
        """
        return self._supports_encryption

    @supports_encryption.setter
    def supports_encryption(self, supports_encryption):
        """Sets the supports_encryption of this StorageProfileSpecification.

        Indicates whether this storage profile supports encryption or not.  # noqa: E501

        :param supports_encryption: The supports_encryption of this StorageProfileSpecification.  # noqa: E501
        :type: bool
        """

        self._supports_encryption = supports_encryption

    @property
    def disk_target_properties(self):
        """Gets the disk_target_properties of this StorageProfileSpecification.  # noqa: E501

        Map of storage placements to know where the disk is provisioned.  # noqa: E501

        :return: The disk_target_properties of this StorageProfileSpecification.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._disk_target_properties

    @disk_target_properties.setter
    def disk_target_properties(self, disk_target_properties):
        """Sets the disk_target_properties of this StorageProfileSpecification.

        Map of storage placements to know where the disk is provisioned.  # noqa: E501

        :param disk_target_properties: The disk_target_properties of this StorageProfileSpecification.  # noqa: E501
        :type: dict(str, str)
        """

        self._disk_target_properties = disk_target_properties

    @property
    def region_id(self):
        """Gets the region_id of this StorageProfileSpecification.  # noqa: E501

        The Id of the region that is associated with the storage profile.  # noqa: E501

        :return: The region_id of this StorageProfileSpecification.  # noqa: E501
        :rtype: str
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this StorageProfileSpecification.

        The Id of the region that is associated with the storage profile.  # noqa: E501

        :param region_id: The region_id of this StorageProfileSpecification.  # noqa: E501
        :type: str
        """
        if region_id is None:
            raise ValueError("Invalid value for `region_id`, must not be `None`")  # noqa: E501

        self._region_id = region_id

    @property
    def name(self):
        """Gets the name of this StorageProfileSpecification.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this StorageProfileSpecification.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StorageProfileSpecification.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this StorageProfileSpecification.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this StorageProfileSpecification.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this StorageProfileSpecification.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this StorageProfileSpecification.

        A human-friendly description.  # noqa: E501

        :param description: The description of this StorageProfileSpecification.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def default_item(self):
        """Gets the default_item of this StorageProfileSpecification.  # noqa: E501

        Indicates if a storage profile is a default profile.  # noqa: E501

        :return: The default_item of this StorageProfileSpecification.  # noqa: E501
        :rtype: bool
        """
        return self._default_item

    @default_item.setter
    def default_item(self, default_item):
        """Sets the default_item of this StorageProfileSpecification.

        Indicates if a storage profile is a default profile.  # noqa: E501

        :param default_item: The default_item of this StorageProfileSpecification.  # noqa: E501
        :type: bool
        """
        if default_item is None:
            raise ValueError("Invalid value for `default_item`, must not be `None`")  # noqa: E501

        self._default_item = default_item

    @property
    def tags(self):
        """Gets the tags of this StorageProfileSpecification.  # noqa: E501

        A list of tags that represent the capabilities of this storage profile  # noqa: E501

        :return: The tags of this StorageProfileSpecification.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this StorageProfileSpecification.

        A list of tags that represent the capabilities of this storage profile  # noqa: E501

        :param tags: The tags of this StorageProfileSpecification.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageProfileSpecification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageProfileSpecification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
