# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VsphereStorageProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'links': 'dict(str, Href)',
        'supports_encryption': 'bool',
        'external_region_id': 'str',
        'shares_level': 'str',
        'description': 'str',
        'disk_mode': 'str',
        'org_id': 'str',
        'tags': 'list[Tag]',
        'organization_id': 'str',
        'shares': 'str',
        'created_at': 'str',
        'provisioning_type': 'str',
        'limit_iops': 'str',
        'name': 'str',
        'id': 'str',
        'default_item': 'bool',
        'updated_at': 'str'
    }

    attribute_map = {
        'owner': 'owner',
        'links': '_links',
        'supports_encryption': 'supportsEncryption',
        'external_region_id': 'externalRegionId',
        'shares_level': 'sharesLevel',
        'description': 'description',
        'disk_mode': 'diskMode',
        'org_id': 'orgId',
        'tags': 'tags',
        'organization_id': 'organizationId',
        'shares': 'shares',
        'created_at': 'createdAt',
        'provisioning_type': 'provisioningType',
        'limit_iops': 'limitIops',
        'name': 'name',
        'id': 'id',
        'default_item': 'defaultItem',
        'updated_at': 'updatedAt'
    }

    def __init__(self, owner=None, links=None, supports_encryption=None, external_region_id=None, shares_level=None, description=None, disk_mode=None, org_id=None, tags=None, organization_id=None, shares=None, created_at=None, provisioning_type=None, limit_iops=None, name=None, id=None, default_item=None, updated_at=None):  # noqa: E501
        """VsphereStorageProfile - a model defined in Swagger"""  # noqa: E501

        self._owner = None
        self._links = None
        self._supports_encryption = None
        self._external_region_id = None
        self._shares_level = None
        self._description = None
        self._disk_mode = None
        self._org_id = None
        self._tags = None
        self._organization_id = None
        self._shares = None
        self._created_at = None
        self._provisioning_type = None
        self._limit_iops = None
        self._name = None
        self._id = None
        self._default_item = None
        self._updated_at = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        self.links = links
        if supports_encryption is not None:
            self.supports_encryption = supports_encryption
        if external_region_id is not None:
            self.external_region_id = external_region_id
        if shares_level is not None:
            self.shares_level = shares_level
        if description is not None:
            self.description = description
        if disk_mode is not None:
            self.disk_mode = disk_mode
        if org_id is not None:
            self.org_id = org_id
        if tags is not None:
            self.tags = tags
        if organization_id is not None:
            self.organization_id = organization_id
        if shares is not None:
            self.shares = shares
        if created_at is not None:
            self.created_at = created_at
        if provisioning_type is not None:
            self.provisioning_type = provisioning_type
        if limit_iops is not None:
            self.limit_iops = limit_iops
        if name is not None:
            self.name = name
        self.id = id
        self.default_item = default_item
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this VsphereStorageProfile.  # noqa: E501

        Email of the user that owns the entity.  # noqa: E501

        :return: The owner of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this VsphereStorageProfile.

        Email of the user that owns the entity.  # noqa: E501

        :param owner: The owner of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def links(self):
        """Gets the links of this VsphereStorageProfile.  # noqa: E501

        HATEOAS of the entity  # noqa: E501

        :return: The links of this VsphereStorageProfile.  # noqa: E501
        :rtype: dict(str, Href)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this VsphereStorageProfile.

        HATEOAS of the entity  # noqa: E501

        :param links: The links of this VsphereStorageProfile.  # noqa: E501
        :type: dict(str, Href)
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def supports_encryption(self):
        """Gets the supports_encryption of this VsphereStorageProfile.  # noqa: E501

        Indicates whether this storage profile should support encryption or not.  # noqa: E501

        :return: The supports_encryption of this VsphereStorageProfile.  # noqa: E501
        :rtype: bool
        """
        return self._supports_encryption

    @supports_encryption.setter
    def supports_encryption(self, supports_encryption):
        """Sets the supports_encryption of this VsphereStorageProfile.

        Indicates whether this storage profile should support encryption or not.  # noqa: E501

        :param supports_encryption: The supports_encryption of this VsphereStorageProfile.  # noqa: E501
        :type: bool
        """

        self._supports_encryption = supports_encryption

    @property
    def external_region_id(self):
        """Gets the external_region_id of this VsphereStorageProfile.  # noqa: E501

        The id of the region for which this profile is defined  # noqa: E501

        :return: The external_region_id of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._external_region_id

    @external_region_id.setter
    def external_region_id(self, external_region_id):
        """Sets the external_region_id of this VsphereStorageProfile.

        The id of the region for which this profile is defined  # noqa: E501

        :param external_region_id: The external_region_id of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._external_region_id = external_region_id

    @property
    def shares_level(self):
        """Gets the shares_level of this VsphereStorageProfile.  # noqa: E501

        Shares level are specified as High, Normal, Low or Custom.  # noqa: E501

        :return: The shares_level of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._shares_level

    @shares_level.setter
    def shares_level(self, shares_level):
        """Sets the shares_level of this VsphereStorageProfile.

        Shares level are specified as High, Normal, Low or Custom.  # noqa: E501

        :param shares_level: The shares_level of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._shares_level = shares_level

    @property
    def description(self):
        """Gets the description of this VsphereStorageProfile.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this VsphereStorageProfile.

        A human-friendly description.  # noqa: E501

        :param description: The description of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def disk_mode(self):
        """Gets the disk_mode of this VsphereStorageProfile.  # noqa: E501

        Type of mode for the disk  # noqa: E501

        :return: The disk_mode of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._disk_mode

    @disk_mode.setter
    def disk_mode(self, disk_mode):
        """Sets the disk_mode of this VsphereStorageProfile.

        Type of mode for the disk  # noqa: E501

        :param disk_mode: The disk_mode of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._disk_mode = disk_mode

    @property
    def org_id(self):
        """Gets the org_id of this VsphereStorageProfile.  # noqa: E501

        The id of the organization this entity belongs to.  # noqa: E501

        :return: The org_id of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this VsphereStorageProfile.

        The id of the organization this entity belongs to.  # noqa: E501

        :param org_id: The org_id of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def tags(self):
        """Gets the tags of this VsphereStorageProfile.  # noqa: E501

        A list of tags that represent the capabilities of this storage profile  # noqa: E501

        :return: The tags of this VsphereStorageProfile.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this VsphereStorageProfile.

        A list of tags that represent the capabilities of this storage profile  # noqa: E501

        :param tags: The tags of this VsphereStorageProfile.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def organization_id(self):
        """Gets the organization_id of this VsphereStorageProfile.  # noqa: E501

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :return: The organization_id of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this VsphereStorageProfile.

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :param organization_id: The organization_id of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def shares(self):
        """Gets the shares of this VsphereStorageProfile.  # noqa: E501

        A specific number of shares assigned to each virtual machine.  # noqa: E501

        :return: The shares of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._shares

    @shares.setter
    def shares(self, shares):
        """Sets the shares of this VsphereStorageProfile.

        A specific number of shares assigned to each virtual machine.  # noqa: E501

        :param shares: The shares of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._shares = shares

    @property
    def created_at(self):
        """Gets the created_at of this VsphereStorageProfile.  # noqa: E501

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :return: The created_at of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this VsphereStorageProfile.

        Date when the entity was created. The date is in ISO 8601 and UTC.  # noqa: E501

        :param created_at: The created_at of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def provisioning_type(self):
        """Gets the provisioning_type of this VsphereStorageProfile.  # noqa: E501

        Type of format for the disk.  # noqa: E501

        :return: The provisioning_type of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._provisioning_type

    @provisioning_type.setter
    def provisioning_type(self, provisioning_type):
        """Sets the provisioning_type of this VsphereStorageProfile.

        Type of format for the disk.  # noqa: E501

        :param provisioning_type: The provisioning_type of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._provisioning_type = provisioning_type

    @property
    def limit_iops(self):
        """Gets the limit_iops of this VsphereStorageProfile.  # noqa: E501

        The upper bound for the I/O operations per second allocated for each disk.  # noqa: E501

        :return: The limit_iops of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._limit_iops

    @limit_iops.setter
    def limit_iops(self, limit_iops):
        """Sets the limit_iops of this VsphereStorageProfile.

        The upper bound for the I/O operations per second allocated for each disk.  # noqa: E501

        :param limit_iops: The limit_iops of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._limit_iops = limit_iops

    @property
    def name(self):
        """Gets the name of this VsphereStorageProfile.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VsphereStorageProfile.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this VsphereStorageProfile.  # noqa: E501

        The id of this resource instance  # noqa: E501

        :return: The id of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VsphereStorageProfile.

        The id of this resource instance  # noqa: E501

        :param id: The id of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def default_item(self):
        """Gets the default_item of this VsphereStorageProfile.  # noqa: E501

        Indicates if a storage profile contains default storage properties.  # noqa: E501

        :return: The default_item of this VsphereStorageProfile.  # noqa: E501
        :rtype: bool
        """
        return self._default_item

    @default_item.setter
    def default_item(self, default_item):
        """Sets the default_item of this VsphereStorageProfile.

        Indicates if a storage profile contains default storage properties.  # noqa: E501

        :param default_item: The default_item of this VsphereStorageProfile.  # noqa: E501
        :type: bool
        """
        if default_item is None:
            raise ValueError("Invalid value for `default_item`, must not be `None`")  # noqa: E501

        self._default_item = default_item

    @property
    def updated_at(self):
        """Gets the updated_at of this VsphereStorageProfile.  # noqa: E501

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :return: The updated_at of this VsphereStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this VsphereStorageProfile.

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :param updated_at: The updated_at of this VsphereStorageProfile.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VsphereStorageProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VsphereStorageProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
