from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from vra_iaas_client.api.about_api import AboutApi
from vra_iaas_client.api.cloud_account_api import CloudAccountApi
from vra_iaas_client.api.compute_api import ComputeApi
from vra_iaas_client.api.data_collector_api import DataCollectorApi
from vra_iaas_client.api.deployment_api import DeploymentApi
from vra_iaas_client.api.disk_api import DiskApi
from vra_iaas_client.api.fabric_aws_volume_types_api import FabricAWSVolumeTypesApi
from vra_iaas_client.api.fabric_azure_storage_account_api import FabricAzureStorageAccountApi
from vra_iaas_client.api.fabric_flavors_api import FabricFlavorsApi
from vra_iaas_client.api.fabric_images_api import FabricImagesApi
from vra_iaas_client.api.fabric_network_api import FabricNetworkApi
from vra_iaas_client.api.fabric_v_sphere_datastore_api import FabricVSphereDatastoreApi
from vra_iaas_client.api.fabric_v_sphere_storage_policies_api import FabricVSphereStoragePoliciesApi
from vra_iaas_client.api.flavor_profile_api import FlavorProfileApi
from vra_iaas_client.api.flavors_api import FlavorsApi
from vra_iaas_client.api.image_profile_api import ImageProfileApi
from vra_iaas_client.api.images_api import ImagesApi
from vra_iaas_client.api.load_balancer_api import LoadBalancerApi
from vra_iaas_client.api.location_api import LocationApi
from vra_iaas_client.api.login_api import LoginApi
from vra_iaas_client.api.network_api import NetworkApi
from vra_iaas_client.api.network_ip_range_api import NetworkIPRangeApi
from vra_iaas_client.api.network_profile_api import NetworkProfileApi
from vra_iaas_client.api.project_api import ProjectApi
from vra_iaas_client.api.request_api import RequestApi
from vra_iaas_client.api.security_group_api import SecurityGroupApi
from vra_iaas_client.api.storage_profile_api import StorageProfileApi
from vra_iaas_client.api.tags_api import TagsApi
